default: &default
  adapter: postgresql
  encoding: utf8
  pool: 20
  timeout: 5000
  username: microblog
  host: localhost

development:
  <<: *default
  database: <%= %Q|#{Rails.root.to_s.split("/").last}_development| %>
  password: microblog

test: &test
  <<: *default
  database: <%= %Q|#{Rails.root.to_s.split("/").last}_test| %>
  password: microblog

cucumber:
  <<: *test
